# Generated by Django 4.2.3 on 2023-09-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_statustracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustracking',
            old_name='status',
            new_name='is_enabled',
        ),
    ]
