# Generated by Django 4.2.3 on 2023-09-22 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0009_alter_statustracking_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='statustracking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statustracking',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
